# Kubernetes Service configuration to expose the nginx deployment

---
# API version for the Service resource (v1 is the stable core API)
apiVersion: v1

# Specifies the type of Kubernetes resource being defined
kind: Service

# METADATA SECTION - Contains data that helps uniquely identify the object
metadata:
  name: nginx
# SPEC SECTION - Defines the desired state of the Service
spec:
  # Selector to identify the Pods that the Service will route traffic to
  selector:
    app: nginx

  # List of ports that the Service will expose
  ports:
    # Port configuration for HTTP and HTTPS
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  # Specifies the type of Service to create
  type: LoadBalancer
